from traits.api import Interface, Instance, List, Str

from .i_multi_image import IMultiImage


class IMultiImageAnalyser(Interface):
    """Interface class that provides requirements any object defines
    analysis of IMultiImage class"""

    #: Reference to multi image under analysis
    multi_image = Instance(IMultiImage)

    #: List of names for each database that will be generated by the
    #: analysis
    database_names = List(Str)

    def image_analysis(self, *args, **kwargs):
        """Perform analysis on data"""

    def create_metrics(self, *args, **kwargs):
        """Create metrics from multi-image components that can be
        generated upon end of analysis"""

    def create_figures(self, *args, **kwargs):
        """Create figures from multi-image components that can be
        generated upon end of analysis"""

    def make_directories(self):
        """Creates required directories for analysis"""
