import networkx as nx

from chaco.api import ArrayPlotData, Plot
from chaco.tools.zoom_tool import ZoomTool
from chaco.tools.pan_tool import PanTool
from chaco.default_colormaps import binary, reverse
from enable.component_editor import ComponentEditor
from traits.api import (
    Instance, Function, List, Int, Property, Str, Enum,
    on_trait_change)
from traitsui.api import Item, View

from pyfibre.core.base_multi_image import BaseMultiImage
from pyfibre.core.base_multi_image_viewer import BaseDisplayTab
from pyfibre.model.tools.figures import (
    create_tensor_image, create_network_image)


class ImageTab(BaseDisplayTab):
    """Standard image tab that just displays raw data for each
    labelled channel in a BaseMultiImage stack"""

    multi_image = Instance(BaseMultiImage)

    cmap = Function(reverse(binary))

    selected_label = Enum(values='image_labels')

    image_plot = Instance(Plot)

    image_data = Instance(ArrayPlotData)

    image_labels = Property(
        List(Str),
        depends_on='multi_image.image_dict'
    )

    trait_view = View(
            Item('image_plot',
                 editor=ComponentEditor(),
                 show_label=False),
            Item('selected_label',
                 style='simple'),
            resizable=True
        )

    def _image_plot_default(self):
        return Plot()

    def _image_data_default(self):
        return ArrayPlotData()

    def _get_image_labels(self):
        """Exposes list of keys for BaseMultiImage.image_dict."""
        if self.multi_image is None:
            return []
        return list(self.multi_image.image_dict.keys())

    @on_trait_change('selected_label')
    def _selected_label_updated(self):
        self._update_image_plot()

    def _update_image_data(self):
        if self.multi_image is None:
            image_dict = {}
        else:
            image_dict = self.multi_image.image_dict
        self.image_data = ArrayPlotData(**image_dict)

    def _update_image_plot(self):

        if self.multi_image is None:
            self.image_plot = Plot()
            return

        if self.image_data is None:
            plot = Plot()
        else:
            plot = Plot(self.image_data)

        # Attach some tools to the plot
        plot.tools.append(
            PanTool(plot, constrain_key="shift"))
        plot.overlays.append(ZoomTool(
            component=plot,
            tool_mode="box",
            always_on=False))

        kwargs = {"origin": 'top left',
                  'axis': 'off'}
        if self.multi_image.ndim == 2:
            kwargs['colormap'] = self.cmap

        if self.selected_label:
            plot.img_plot(
                self.selected_label,
                **kwargs)

        self.image_plot = plot

    def reset_tab(self):
        self.multi_image = None
        self.update_tab()

    def update_tab(self):
        """Provide additional customisation to chaco Plot object
        generated by this class."""
        self._update_image_data()
        self._update_image_plot()

    def customise_plot(self, plot):
        """Attach optional tools to plot"""
        pass


class TensorImageTab(ImageTab):

    def _tensor_image(self, image):
        return create_tensor_image(image)

    def _update_image_data(self):
        """Convert each image into a tensor image"""
        if self.multi_image is None:
            image_dict = {}
        else:
            image_dict = {
                label: self._tensor_image(image).astype('uint8')
                for label, image in self.multi_image.image_dict.items()}
        self.image_data = ArrayPlotData(**image_dict)


class NetworkImageTab(ImageTab):

    networks = List(nx.Graph)

    c_mode = Int(0)

    def _network_image(self, image):
        return create_network_image(
            image,
            self.networks,
            c_mode=self.c_mode)

    def _update_image_data(self):
        """Convert each image into a network image"""
        if self.multi_image is None:
            image_dict = {}
        else:
            image_dict = {
                label: self._network_image(image).astype('uint8')
                for label, image in self.multi_image.image_dict.items()}
        self.image_data = ArrayPlotData(**image_dict)

    def reset_tab(self):
        self.networks = []
        super().reset_tab()
