name: Pyfibre CI tests

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Build project environment
      run: uv sync --frozen

    - name: Test with unittest
      run: uv run -m unittest discover

    - name: Run coverage
      run: uv run -m coverage run -m unittest discover

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: htmlcov/

    - name: Perform integration test
      run: edm run PyFibre --test
