# This workflow runs flake8 checks on the code base

name: Style check

on: pull_request

jobs:
  style:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Run style checks
      run: uvx ruff check